package MODEL;

import java.time.LocalDateTime;

public class Transaction {
    private int id;
    private int accountId;
    private double amount;
    private LocalDateTime date;
    private String type; // deposit/withdrawal

    // Use this constructor for creating new transactions (ID auto-generated by DB)
    public Transaction(int accountId, double amount, LocalDateTime date, String type) {
        this.accountId = accountId;
        this.amount = amount;
        this.date = date;
        this.type = type;
    }

    // Full constructor (used when fetching from DB)
    public Transaction(int id, int accountId, double amount, LocalDateTime date, String type) {
        this.id = id;
        this.accountId = accountId;
        this.amount = amount;
        this.date = date;
        this.type = type;
    }

    // Getters & setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getAccountId() { return accountId; }
    public void setAccountId(int accountId) { this.accountId = accountId; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public LocalDateTime getDate() { return date; }
    public void setDate(LocalDateTime date) { this.date = date; }

    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    @Override
    public String toString() {
        return "Transaction [id=" + id + ", accountId=" + accountId + ", amount=" + amount +
               ", date=" + date + ", type=" + type + "]";
    }
}
